<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Enums\RoomType;
use App\Enums\Tags;
use App\Enums\TypeCategory;
use App\Models\Blog;
use App\Models\Category;
use App\Models\Room;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Tags\Tag;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);
        User::factory()->create();
        Tag::findOrCreate('#', Tags::Blog);
        Tag::findOrCreate('#', Tags::RoomService['general_amenities']);
        Tag::findOrCreate('#', Tags::RoomService['outdoor_facilities']);

        Category::insert([
            [
                'name' => '#',
                'type' => TypeCategory::Room,
            ],
            [
                'name' => '#',
                'type' => TypeCategory::Blog,
            ]
        ]);

        $roomData = [
            [
                'name' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã 202',
                'room_type' => RoomType::Studio,
                'description' => "Tòa nhà a10/ngách 19/ngõ 535 Kim Mã. Full đồ nội thất (giường,tủ,tủ lạnh,đồ bếp, máy giặt sấy, bồn tắm nằm, hầm để xe, ô tô đỗ cửa, cách hồ ngọc khánh 20m, đằng sau trường RMIT). <br>GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT. Bình nóng lạnh 80L",
                'acreage' => 40,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 400,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã 302',
                'room_type' => RoomType::Studio,
                'description' => "Tòa nhà a10/ngách 19/ngõ 535 Kim Mã. Full đồ nội thất (giường,tủ,tủ lạnh,đồ bếp, máy giặt sấy, bồn tắm nằm, hầm để xe, ô tô đỗ cửa, cách hồ ngọc khánh 20m, đằng sau trường RMIT). <br>GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT. Bình nóng lạnh 80L",
                'acreage' => 40,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 450,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã 402',
                'room_type' => RoomType::Studio,
                'description' => "Tòa nhà a10/ngách 19/ngõ 535 Kim Mã. Full đồ nội thất (giường,tủ,tủ lạnh,đồ bếp, máy giặt sấy, bồn tắm nằm, hầm để xe, ô tô đỗ cửa, cách hồ ngọc khánh 20m, đằng sau trường RMIT). <br>GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT. Bình nóng lạnh 80L",
                'acreage' => 40,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 450,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã 702',
                'room_type' => RoomType::Studio,
                'description' => "Tòa nhà a10/ngách 19/ngõ 535 Kim Mã. Full đồ nội thất (giường,tủ,tủ lạnh,đồ bếp, máy giặt sấy, bồn tắm nằm, hầm để xe, ô tô đỗ cửa, cách hồ ngọc khánh 20m, đằng sau trường RMIT). <br>GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT. Bình nóng lạnh 80L",
                'acreage' => 40,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 400,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã 801',
                'room_type' => RoomType::Studio,
                'description' => "Tòa nhà a10/ngách 19/ngõ 535 Kim Mã. Full đồ nội thất (giường,tủ,tủ lạnh,đồ bếp, máy giặt sấy, bồn tắm nằm, hầm để xe, ô tô đỗ cửa, cách hồ ngọc khánh 20m, đằng sau trường RMIT). <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT. Bình nóng lạnh 80L",
                'acreage' => 40,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà a10/ngách 19/ngõ 535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 550,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ], //done batch no 1
            [
                'name' => 'Tòa nhà 34 ngõ 12 đào tấn 101',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà 34 ngõ 12 đào tấn (14 căn hộ 1 ngủ, 1 căn hộ studio lớn, full đồ, thoáng, sáng, gần Lotte, thang máy, bồn tắm nằm. <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 34 ngõ 12 đào tấn',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 470,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà 34 ngõ 12 đào tấn 301',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà 34 ngõ 12 đào tấn (14 căn hộ 1 ngủ, 1 căn hộ studio lớn, full đồ, thoáng, sáng, gần Lotte, thang máy, bồn tắm nằm. <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 34 ngõ 12 đào tấn',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 500,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà 34 ngõ 12 đào tấn 302',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà 34 ngõ 12 đào tấn (14 căn hộ 1 ngủ, 1 căn hộ studio lớn, full đồ, thoáng, sáng, gần Lotte, thang máy, bồn tắm nằm. <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 34 ngõ 12 đào tấn',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 500,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà 34 ngõ 12 đào tấn 403',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà 34 ngõ 12 đào tấn (14 căn hộ 1 ngủ, 1 căn hộ studio lớn, full đồ, thoáng, sáng, gần Lotte, thang máy, bồn tắm nằm. <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 34 ngõ 12 đào tấn',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 500,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà 34 ngõ 12 đào tấn 601',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà 34 ngõ 12 đào tấn (14 căn hộ 1 ngủ, 1 căn hộ studio lớn, full đồ, thoáng, sáng, gần Lotte, thang máy, bồn tắm nằm. <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 34 ngõ 12 đào tấn',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 550,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà 34 ngõ 12 đào tấn 603',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà 34 ngõ 12 đào tấn (14 căn hộ 1 ngủ, 1 căn hộ studio lớn, full đồ, thoáng, sáng, gần Lotte, thang máy, bồn tắm nằm. <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 34 ngõ 12 đào tấn',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 600,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            // end batch no 2
            [
                'name' => 'Tòa nhà 103-A4 Lạc Chính, Trúc Bạch, Ba Đình 101',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà 103-A4 Lạc Chính, Trúc Bạch, Ba Đình. ( Full đồ nội thất cao cấp, có máy giặt sấy riêng từng phòng). Vị Trí: ô tô đỗ cửa, cách hồ Trúc Bạch 20m, tầng cao view hồ. Gồm 5 căn 2N1K, 2 căn 1N1K, 1 căn Pen House). <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 85,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 103-A4 Lạc Chính, Trúc Bạch',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 600,
                'unit' => 'month',
                'bedroom' => 2,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà 103-A4 Lạc Chính, Trúc Bạch, Ba Đình tầng 7 8 9 Duplex',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà 103-A4 Lạc Chính, Trúc Bạch, Ba Đình. ( Full đồ nội thất cao cấp, có máy giặt sấy riêng từng phòng). Vị Trí: ô tô đỗ cửa, cách hồ Trúc Bạch 20m, tầng cao view hồ. Gồm 5 căn 2N1K, 2 căn 1N1K, 1 căn Pen House). <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 300,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 103-A4 Lạc Chính, Trúc Bạch',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 3000,
                'unit' => 'month',
                'bedroom' => 4,
                'bathroom' => 1,
            ],
            // done batch no 3
            [
                'name' => 'Tòa nhà số 2 ngõ 224 Bưởi, Cống Vị, Ba Đình 202',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 2 ngõ 224 Bưởi, Cống Vị, Ba Đình. ( Full đồ nội thất , Máy giặt sấy chung, có bảo vệ 24/24). Vị Trí: ô tô đỗ cách nhà 10m. Gồm 15 căn hộ. <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 40,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 2 ngõ 224 Bưởi, Cống Vị',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 450,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            //done batch no 4
            [
                'name' => 'Tòa nhà số B5 ngõ 535 Kim Mã, Ngọc Khánh, Ba Đình 401',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số B5 ngõ 535 Kim Mã, Ngọc Khánh, Ba Đình. ( Full đồ nội thất , Máy giặt sấy chung). Vị Trí: Gần trường RMIT, cách hồ ngọc khánh 50m. Gồm 7 căn hộ 1N1K. <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 60,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 103-A4 Lạc Chính, Trúc Bạch',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 500,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số B5 ngõ 535 Kim Mã, Ngọc Khánh, Ba Đình 701',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số B5 ngõ 535 Kim Mã, Ngọc Khánh, Ba Đình. ( Full đồ nội thất , Máy giặt sấy chung). Vị Trí: Gần trường RMIT, cách hồ ngọc khánh 50m. Gồm 7 căn hộ 1N1K. <br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 60,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà 103-A4 Lạc Chính, Trúc Bạch',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 500,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            //done batch no 5
            [
                'name' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình 301',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình. Gồm 13 căn hộ, 2 văn phòng ( Full đồ nội thất , Máy giặt sấy chung, có bồn tắm). Vị Trí:cách 10m mặt đường đào tấn, gần nguyễn khánh toàn, bưởi.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 500,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình 302',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình. Gồm 13 căn hộ, 2 văn phòng ( Full đồ nội thất , Máy giặt sấy chung, có bồn tắm). Vị Trí:cách 10m mặt đường đào tấn, gần nguyễn khánh toàn, bưởi.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 40,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị',
                'start_date' => Carbon::parse('2024-02-15'),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 500,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình 401',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình. Gồm 13 căn hộ, 2 văn phòng ( Full đồ nội thất , Máy giặt sấy chung, có bồn tắm). Vị Trí:cách 10m mặt đường đào tấn, gần nguyễn khánh toàn, bưởi.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 500,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình 402',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình. Gồm 13 căn hộ, 2 văn phòng ( Full đồ nội thất , Máy giặt sấy chung, có bồn tắm). Vị Trí:cách 10m mặt đường đào tấn, gần nguyễn khánh toàn, bưởi.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 450,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình 403',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị, Ba Đình. Gồm 13 căn hộ, 2 văn phòng ( Full đồ nội thất , Máy giặt sấy chung, có bồn tắm). Vị Trí:cách 10m mặt đường đào tấn, gần nguyễn khánh toàn, bưởi.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 2A ngõ 92 Đào Tấn, Cống Vị',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 450,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            //done batch no 6
            [
                'name' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ  MBKD',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ. ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Mặt hồ tây, gần đường thanh niên, chùa trấn quốc, yên phụ. Gồm 1 MBKD + 8 căn hộ.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 60,
                'province' => 1,
                'district' => 3,
                'address' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ ',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 600,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ  201',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ. ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Mặt hồ tây, gần đường thanh niên, chùa trấn quốc, yên phụ. Gồm 1 MBKD + 8 căn hộ.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 35,
                'province' => 1,
                'district' => 3,
                'address' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ ',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 600,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ  202',
                'room_type' => RoomType::Studio,
                'description' => "Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ. ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Mặt hồ tây, gần đường thanh niên, chùa trấn quốc, yên phụ. Gồm 1 MBKD + 8 căn hộ.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 35,
                'province' => 1,
                'district' => 3,
                'address' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ ',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 350,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ  302',
                'room_type' => RoomType::Studio,
                'description' => "Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ. ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Mặt hồ tây, gần đường thanh niên, chùa trấn quốc, yên phụ. Gồm 1 MBKD + 8 căn hộ.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 35,
                'province' => 1,
                'district' => 3,
                'address' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ ',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 350,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ  502',
                'room_type' => RoomType::Studio,
                'description' => "Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ. ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Mặt hồ tây, gần đường thanh niên, chùa trấn quốc, yên phụ. Gồm 1 MBKD + 8 căn hộ.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 35,
                'province' => 1,
                'district' => 3,
                'address' => 'Tòa nhà số 30 Yên Hoa, Yên Phụ Tây Hồ ',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 350,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            //done batch no 9
            [
                'name' => 'Tòa nhà số 22/2/535 Kim Mã 302',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 22/2/535 Kim Mã ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Ô tô đỗ cửa, cách hồ Phạm Huy Thông 30m, gần trưởng RMIT.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 22/2/535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 700,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 22/2/535 Kim Mã 501',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 22/2/535 Kim Mã ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Ô tô đỗ cửa, cách hồ Phạm Huy Thông 30m, gần trưởng RMIT.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 22/2/535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 800,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 22/2/535 Kim Mã 502',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 22/2/535 Kim Mã ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Ô tô đỗ cửa, cách hồ Phạm Huy Thông 30m, gần trưởng RMIT.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 22/2/535 Kim Mã',
                'start_date' => Carbon::parse('2024-02-09'),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 750,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 22/2/535 Kim Mã 601',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 22/2/535 Kim Mã ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Ô tô đỗ cửa, cách hồ Phạm Huy Thông 30m, gần trưởng RMIT.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 22/2/535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 900,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 22/2/535 Kim Mã 602',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 22/2/535 Kim Mã ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Ô tô đỗ cửa, cách hồ Phạm Huy Thông 30m, gần trưởng RMIT.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 22/2/535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 800,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 22/2/535 Kim Mã 801',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 22/2/535 Kim Mã ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Ô tô đỗ cửa, cách hồ Phạm Huy Thông 30m, gần trưởng RMIT.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 22/2/535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 900,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa nhà số 22/2/535 Kim Mã 802',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa nhà số 22/2/535 Kim Mã ( Full đồ nội thất , Máy giặt riêng từng phòng). Vị Trí: Ô tô đỗ cửa, cách hồ Phạm Huy Thông 30m, gần trưởng RMIT.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa nhà số 22/2/535 Kim Mã',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 900,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            //done batch no 10
            [
                'name' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình 101',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 42 Ngõ 290 Kim Mã, Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 380,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình 201',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 42 Ngõ 290 Kim Mã, Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 450,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình 202',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 42 Ngõ 290 Kim Mã, Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 400,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình 301',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 42 Ngõ 290 Kim Mã, Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 450,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình 302',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 42 Ngõ 290 Kim Mã, Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 400,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình 402',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 42 Ngõ 290 Kim Mã, Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 45,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 42 Ngõ 290 Kim Mã, Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 400,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            // done batch no 13
            [
                'name' => 'Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình 201',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn, máy giặt sấy,tivi) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 80,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 650,
                'unit' => 'month',
                'bedroom' => 2,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình 301',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn, máy giặt sấy,tivi) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 80,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 650,
                'unit' => 'month',
                'bedroom' => 2,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình 401',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn, máy giặt sấy,tivi) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 80,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 680,
                'unit' => 'month',
                'bedroom' => 2,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình 501',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, tủ bếp trên dưới hút mùi, đệm, lò vi sóng, sofa bàn trà, bàn ăn, máy giặt sấy,tivi) . Vị Trí: gần Lotte, Núi Trúc, Nguyễn Thái Học, Bảo Khánh.<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 80,
                'province' => 1,
                'district' => 1,
                'address' => 'Tòa 83/68/173 HOÀNG HOA THÁM( Đình Đại Yên ngõ 279 Đội Cấn), Ba Đình',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 680,
                'unit' => 'month',
                'bedroom' => 2,
                'bathroom' => 1,
            ],
            // done batch no 14
            [
                'name' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy Tầng 1 MBKD',
                'room_type' => RoomType::Apartments,
                'description' => "Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, Tủ bếp( có hút mùi ko có bếp từ), bàn ăn) Máy giặt sấy chung tầng 6. Vị Trí: gần Láng, Nguyễn Khang, Cầu Giấy, Kim Mã, Thái Hà, Ngã Tư Sở).<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 20,
                'province' => 1,
                'district' => 5,
                'address' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 300,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy Tầng 201',
                'room_type' => RoomType::Studio,
                'description' => "Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, Tủ bếp( có hút mùi ko có bếp từ), bàn ăn) Máy giặt sấy chung tầng 6. Vị Trí: gần Láng, Nguyễn Khang, Cầu Giấy, Kim Mã, Thái Hà, Ngã Tư Sở).<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 30,
                'province' => 1,
                'district' => 5,
                'address' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 300,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy Tầng 202',
                'room_type' => RoomType::Studio,
                'description' => "Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, Tủ bếp( có hút mùi ko có bếp từ), bàn ăn) Máy giặt sấy chung tầng 6. Vị Trí: gần Láng, Nguyễn Khang, Cầu Giấy, Kim Mã, Thái Hà, Ngã Tư Sở).<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 40,
                'province' => 1,
                'district' => 5,
                'address' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 320,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy Tầng 301',
                'room_type' => RoomType::Studio,
                'description' => "Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, Tủ bếp( có hút mùi ko có bếp từ), bàn ăn) Máy giặt sấy chung tầng 6. Vị Trí: gần Láng, Nguyễn Khang, Cầu Giấy, Kim Mã, Thái Hà, Ngã Tư Sở).<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 30,
                'province' => 1,
                'district' => 5,
                'address' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 300,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy Tầng 302',
                'room_type' => RoomType::Studio,
                'description' => "Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, Tủ bếp( có hút mùi ko có bếp từ), bàn ăn) Máy giặt sấy chung tầng 6. Vị Trí: gần Láng, Nguyễn Khang, Cầu Giấy, Kim Mã, Thái Hà, Ngã Tư Sở).<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 40,
                'province' => 1,
                'district' => 5,
                'address' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 320,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy Tầng 401',
                'room_type' => RoomType::Studio,
                'description' => "Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, Tủ bếp( có hút mùi ko có bếp từ), bàn ăn) Máy giặt sấy chung tầng 6. Vị Trí: gần Láng, Nguyễn Khang, Cầu Giấy, Kim Mã, Thái Hà, Ngã Tư Sở).<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 30,
                'province' => 1,
                'district' => 5,
                'address' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 300,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy Tầng 402',
                'room_type' => RoomType::Studio,
                'description' => "Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, Tủ bếp( có hút mùi ko có bếp từ), bàn ăn) Máy giặt sấy chung tầng 6. Vị Trí: gần Láng, Nguyễn Khang, Cầu Giấy, Kim Mã, Thái Hà, Ngã Tư Sở).<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 40,
                'province' => 1,
                'district' => 5,
                'address' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 320,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
            [
                'name' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy Tầng 501',
                'room_type' => RoomType::Studio,
                'description' => "Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy. ( Nội thất giường tủ, tủ lạnh, điều hòa, nóng lạnh, Tủ bếp( có hút mùi ko có bếp từ), bàn ăn) Máy giặt sấy chung tầng 6. Vị Trí: gần Láng, Nguyễn Khang, Cầu Giấy, Kim Mã, Thái Hà, Ngã Tư Sở).<br> GIÁ ĐÃ BAO GỒM (Dọn phòng và giặt đồ 2 lần/tuần,nước sinh hoạt, vệ sinh chung, wifi, điện nước máy giặt chung, bảo trì thang máy, bảo vệ 24/24, gửi 1 xe máy).Chưa bao gồm VAT, Tiền điện 3.900đ/1 số,. KHÔNG NUÔI ĐỘNG VẬT.",
                'acreage' => 30,
                'province' => 1,
                'district' => 5,
                'address' => 'Tòa 16 Ngõ 113 Yên Hòa, Cầu Giấy',
                'start_date' => now(),
                'end_date' =>Carbon::now()->endOfYear()->format('Y-m-d'),
                'price' => 300,
                'unit' => 'month',
                'bedroom' => 1,
                'bathroom' => 1,
            ],
        ];

        foreach ($roomData as $key => $data) {
            $room = Room::create($data);

            $roomCategory = Category::where('type', TypeCategory::Room)->first();
            $roomTags = Tag::whereIn('type', Tags::RoomService)->get();
            foreach ($roomTags as $key => $tag) {
                $room->attachTags([$tag->name], $tag->type);
            }
            $room->categories()->attach($roomCategory->id, [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        DB::unprepared(file_get_contents(public_path('/location.sql')));
    }

}
